services:
  # Backend Flask application
  - type: web
    name: hosseinx-bot3-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hosseinx-bot3-db
          property: connectionString

  # Frontend Next.js application
  - type: web
    name: hosseinx-bot3-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: hosseinx-bot3-backend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: hosseinx-bot3-db
    plan: free